### ISSUE TITLE
Background tabs opening the first item, not the currently selected item

### ISSUE THREAD

**Issue by TallBaldGeek** [k-yogo/feedly-background-tab-open#1]
I am viewing Feedly using the "article" view. When opening an item using the background tab extension, a new tab is opened but it's always opening whatever the first item in the list was, not the currently selected item. 

If it helps, I use the built-in Feedly shortcuts "J" and "K" to navigate next/previous in the article list. I looked in the Chrome debugger console when opening an article in the background but I didn't see any related errors.

Thanks for the extension!

**Comment by k-yogo** [comment]
Thank you for your comment and for sharing the bug with me.
I removed the code as unnecessary and it no longer works in Article View.
I had not noticed it at all, so it was a big help.
I have fixed it in Ver 1.24, so please update your extension to use it.
Thank you very much for your cooperation!

**Comment by TallBaldGeek** [comment]
Updated to v1.24 and confirmed it's working as expected for Article view. Thanks!
